/*
 * File: app/view/EventPanel1.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.EventPanel1', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.EventPanel1',

    cls: 'event-panel1',
    preventHeader: true,
    title: 'AddFundil',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'component',
                    cls: 'logo',
                    id: 'logo'
                },
                {
                    xtype: 'form',
                    cls: 'main',
                    id: 'createEventForm1',
                    layout: {
                        type: 'auto'
                    },
                    bodyPadding: 10,
                    frameHeader: false,
                    preventHeader: true,
                    title: 'Event Form',
                    items: [
                        {
                            xtype: 'component',
                            id: 'step1of2',
                            renderTpl: [
                                'Step 1 of 2'
                            ]
                        },
                        {
                            xtype: 'component',
                            cls: 'help-line',
                            id: 'loginHelpLine',
                            stateful: false
                        },
                        {
                            xtype: 'container',
                            id: 'formWrapper',
                            width: 300,
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    placeHolder: 'Email',
                                    flex: 1,
                                    cls: 'event first',
                                    name: 'eventTitle',
                                    validateOnBlur: false,
                                    validateOnChange: false,
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    labelWidth: 0,
                                    allowBlank: false,
                                    blankText: 'Required',
                                    emptyText: 'Title'
                                },
                                {
                                    xtype: 'datefield',
                                    flex: 1,
                                    name: 'eventDate',
                                    validateOnBlur: false,
                                    validateOnChange: false,
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    emptyText: 'Date',
                                    hideTrigger: false,
                                    repeatTriggerClick: false,
                                    pickerAlign: 'tl-bl'
                                },
                                {
                                    xtype: 'timefield',
                                    flex: 1,
                                    shadow: 'none',
                                    name: 'eventStartTime',
                                    validateOnBlur: false,
                                    validateOnChange: false,
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    emptyText: 'Start Time'
                                },
                                {
                                    xtype: 'timefield',
                                    flex: 1,
                                    hidden: true,
                                    shadow: 'none',
                                    name: 'eventEndTime',
                                    validateOnBlur: false,
                                    validateOnChange: false,
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    emptyText: 'End Time'
                                },
                                {
                                    xtype: 'textfield',
                                    placeHolder: 'Password',
                                    flex: 1,
                                    cls: 'location last',
                                    name: 'eventLocation',
                                    validateOnBlur: false,
                                    validateOnChange: false,
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    labelWidth: 0,
                                    allowBlank: false,
                                    blankText: 'Password',
                                    emptyText: 'Location',
                                    enforceMaxLength: true,
                                    maxLength: 30,
                                    minLength: 3,
                                    size: 30
                                }
                            ]
                        },
                        {
                            xtype: 'button',
                            cls: 'last',
                            id: 'step1Next',
                            text: 'Next'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});