/*
 * File: app/view/EventPanel2.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.EventPanel2', {
    extend: 'Ext.panel.Panel',

    cls: 'event-panel2',
    preventHeader: true,
    title: 'AddFundil',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'component',
                    cls: 'logo',
                    id: 'logo'
                },
                {
                    xtype: 'form',
                    cls: 'main',
                    id: 'createEventForm2',
                    layout: {
                        type: 'auto'
                    },
                    bodyPadding: 10,
                    frameHeader: false,
                    preventHeader: true,
                    title: 'Event Form',
                    items: [
                        {
                            xtype: 'component',
                            id: 'step2of2',
                            renderTpl: [
                                'Step 2 of 2'
                            ]
                        },
                        {
                            xtype: 'component',
                            cls: 'help-line',
                            id: 'loginHelpLine',
                            stateful: false
                        },
                        {
                            xtype: 'container',
                            id: 'formWrapper',
                            width: 300,
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            items: [
                                {
                                    xtype: 'textareafield',
                                    flex: 1,
                                    cls: 'first description',
                                    disabled: false,
                                    stateful: false,
                                    focusOnToFront: false,
                                    name: 'eventDescription',
                                    validateOnBlur: false,
                                    validateOnChange: false,
                                    autoFitErrors: false,
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    labelWidth: 0,
                                    allowBlank: false,
                                    blankText: 'Required',
                                    emptyText: 'about the event'
                                },
                                {
                                    xtype: 'combobox',
                                    flex: 1,
                                    cls: 'invitees',
                                    id: 'eventInvitees',
                                    stateful: false,
                                    name: 'eventInvitees',
                                    validateOnBlur: false,
                                    validateOnChange: false,
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    emptyText: 'select invitees/funders',
                                    displayField: 'invitee',
                                    minChars: 1,
                                    multiSelect: true,
                                    queryMode: 'local',
                                    store: 'userContacts',
                                    typeAhead: false,
                                    valueNotFoundText: 'No match'
                                },
                                {
                                    xtype: 'textareafield',
                                    placeholder: 'eventItems',
                                    flex: 1,
                                    cls: 'last items',
                                    disabled: false,
                                    id: 'eventItems',
                                    stateful: false,
                                    name: 'eventItems',
                                    validateOnBlur: false,
                                    validateOnChange: false,
                                    autoFitErrors: false,
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    labelWidth: 0,
                                    allowBlank: false,
                                    blankText: 'Required',
                                    emptyText: '\n items i need funding for (optional)'
                                }
                            ]
                        },
                        {
                            xtype: 'button',
                            cls: '',
                            id: 'step2Back',
                            text: 'Back'
                        },
                        {
                            xtype: 'button',
                            cls: 'last',
                            id: 'step2Next',
                            text: 'Next'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});