/*
 * File: app/view/LoginPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.LoginPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.LoginPanel',

    cls: 'login-panel',
    id: 'LoginPanel',
    preventHeader: true,
    title: 'LoginPanel',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'component',
                    cls: 'logo',
                    id: 'logo'
                },
                {
                    xtype: 'form',
                    cls: 'main',
                    id: 'loginForm',
                    layout: {
                        type: 'auto'
                    },
                    bodyPadding: 10,
                    frameHeader: false,
                    preventHeader: true,
                    title: 'Login Form',
                    items: [
                        {
                            xtype: 'component',
                            id: 'PlanningAnEvent',
                            renderTpl: [
                                'Planning an event?'
                            ]
                        },
                        {
                            xtype: 'component',
                            id: 'WantHelpFromFriends',
                            renderTpl: [
                                'Want some help from friends?'
                            ]
                        },
                        {
                            xtype: 'component',
                            id: 'FundilioMakesItEasy',
                            renderTpl: [
                                'Good! Cause Fundilio makes it easy.'
                            ]
                        },
                        {
                            xtype: 'component',
                            cls: 'help-line',
                            id: 'loginHelpLine',
                            stateful: false
                        },
                        {
                            xtype: 'container',
                            id: 'formWrapper',
                            width: 300,
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    placeHolder: 'Email',
                                    flex: 1,
                                    cls: 'email first',
                                    id: 'loginName',
                                    name: 'email',
                                    validateOnBlur: false,
                                    validateOnChange: false,
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    labelWidth: 0,
                                    allowBlank: false,
                                    blankText: 'Required',
                                    emptyText: 'Email'
                                },
                                {
                                    xtype: 'textfield',
                                    placeHolder: 'Password',
                                    flex: 1,
                                    cls: 'password last',
                                    id: 'loginPass',
                                    inputType: 'password',
                                    name: 'password',
                                    validateOnBlur: false,
                                    validateOnChange: false,
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    labelWidth: 0,
                                    allowBlank: false,
                                    blankText: 'Password',
                                    emptyText: 'Password',
                                    enforceMaxLength: true,
                                    maxLength: 30,
                                    minLength: 3,
                                    size: 30
                                }
                            ]
                        },
                        {
                            xtype: 'button',
                            id: 'registerButton',
                            text: 'Register'
                        },
                        {
                            xtype: 'button',
                            cls: '',
                            id: 'loginButton',
                            text: 'Login'
                        },
                        {
                            xtype: 'button',
                            cls: 'last',
                            id: 'loginFBButton',
                            text: 'FB Login'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});