/*
 * File: app/view/SettingsBar.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.SettingsBar', {
    extend: 'Ext.container.Container',

    cls: 'settings-bar',
    id: 'SettingsBar',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'button',
                    cls: 'createEvent-btn',
                    id: 'createEventButton',
                    text: 'Create Event'
                },
                {
                    xtype: 'button',
                    cls: 'logout-btn',
                    id: 'myAccountButton',
                    text: 'My Account'
                },
                {
                    xtype: 'button',
                    cls: 'logout-btn',
                    id: 'logoutButton',
                    text: 'Logout'
                }
            ]
        });

        me.callParent(arguments);
    }

});