/*
 * File: app/view/SummaryPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.SummaryPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.SummaryPanel',

    cls: 'summary-panel',
    id: 'SummaryPanel',
    preventHeader: true,
    title: 'AddFundil',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'component',
                    cls: 'logo',
                    id: 'logo'
                },
                {
                    xtype: 'form',
                    cls: 'main',
                    layout: {
                        type: 'auto'
                    },
                    bodyPadding: 10,
                    frameHeader: false,
                    preventHeader: true,
                    title: 'Event Form',
                    items: [
                        {
                            xtype: 'component',
                            cls: 'summaryText',
                            id: 'summaryText',
                            renderTpl: [
                                'Summary'
                            ]
                        },
                        {
                            xtype: 'component',
                            cls: 'summarySub half',
                            id: 'summarySub',
                            renderTpl: [
                                '(what funders will see)'
                            ]
                        },
                        {
                            xtype: 'container',
                            id: 'formWrapper',
                            width: 300,
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    cls: '',
                                    id: 'fundingWrapper',
                                    items: [
                                        {
                                            xtype: 'container',
                                            cls: 'summaryDetailWrapper wrapper first',
                                            id: 'summaryDetailWrapper',
                                            items: [
                                                {
                                                    xtype: 'component',
                                                    cls: 'wrapped',
                                                    id: 'summaryTitle',
                                                    renderTpl: [
                                                        '{[FundilioUser.loadedEvent.title]}'
                                                    ]
                                                },
                                                {
                                                    xtype: 'component',
                                                    cls: 'wrapped',
                                                    hidden: true,
                                                    id: 'summarySubTitle',
                                                    renderTpl: [
                                                        '{[FundilioUser.loadedEvent.description]}'
                                                    ]
                                                },
                                                {
                                                    xtype: 'component',
                                                    cls: 'wrapped',
                                                    id: 'summaryTime',
                                                    renderTpl: [
                                                        '{[FundilioUser.loadedEvent.date]} @ {[FundilioUser.loadedEvent.startTime]}'
                                                    ]
                                                },
                                                {
                                                    xtype: 'component',
                                                    cls: 'wrapped',
                                                    id: 'summaryLocation',
                                                    renderTpl: [
                                                        '{[FundilioUser.loadedEvent.location]}'
                                                    ]
                                                },
                                                {
                                                    xtype: 'component',
                                                    cls: 'wrapped',
                                                    id: 'summaryDescription',
                                                    renderTpl: [
                                                        '{[FundilioUser.loadedEvent.description]}'
                                                    ]
                                                },
                                                {
                                                    xtype: 'component',
                                                    cls: 'wrapped',
                                                    id: 'summaryItems',
                                                    renderTpl: [
                                                        '{[FundilioUser.loadedEvent.items]}'
                                                    ]
                                                },
                                                {
                                                    xtype: 'component',
                                                    cls: 'wrapped',
                                                    id: 'summaryFundingLimit',
                                                    renderTpl: [
                                                        'Guest funding limit: $15.00'
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            cls: 'fundingDetailWrapper wrapper last',
                                            id: 'fundingDetailWrapper',
                                            minHeight: 60,
                                            items: [
                                                {
                                                    xtype: 'component',
                                                    cls: 'wrapped unlit',
                                                    id: 'fundingDetailPrev',
                                                    renderTpl: [
                                                        '$'
                                                    ]
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    placeHolder: 'Email',
                                                    cls: 'fundingLimit wrapped',
                                                    disabled: false,
                                                    id: 'fundingLimit',
                                                    inputType: 'int',
                                                    name: 'fundingLimit',
                                                    fieldLabel: 'Label',
                                                    hideLabel: true,
                                                    labelWidth: 0,
                                                    allowBlank: false,
                                                    blankText: 'Required',
                                                    emptyText: '0',
                                                    size: 2
                                                },
                                                {
                                                    xtype: 'component',
                                                    cls: 'wrapped unlit',
                                                    id: 'fundingDetailAfter',
                                                    renderTpl: [
                                                        '.00'
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'button',
                            cls: '',
                            id: 'edit',
                            text: 'Edit'
                        },
                        {
                            xtype: 'button',
                            cls: 'last',
                            id: 'send',
                            text: 'Send'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});